[package]
name = "mavlink-bindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc-any = { workspace = true, default-features = false }
quick-xml = "0.26"
quote = "1"
proc-macro2 = "1.0.43"
lazy_static = "1.2.0"
serde = { version = "1.0.115", optional = true, features = ["derive"] }
clap = { version = "~4.3.24", features = ["derive"] }
# Required to support MSRV 1.65.0
clap_lex = { version = "=0.5.0" }
thiserror = "1.0.56"
